#!/bin/sh

set -e

# first choice is curl(1), should be OK for Linux
if command -v curl >/dev/null 2>&1; then
  __download () {
    curl -s "$1"
  }
# second is fetch(1), for FreeBSD
elif command -v fetch >/dev/null 2>&1; then
  __download () {
    fetch -q -o - "$1"
  }
# last comes ftp(1), which does far more than its name implies (OpenBSD only)
elif [ "$(uname -s)" = OpenBSD ] && command -v ftp >/dev/null 2>&1; then
  __download () {
    ftp -o - "$1"
  }
else
  printf '%s\n' "Oh no! You don't seem to have curl(1) or fetch(1)" >&2
  printf '%s\n' "I'm cowardly exiting" >&2
  exit 4
fi

# Archlinux
__download 'https://www.archlinux.org/download/' |grep -Eo 'magnet:[^"]+'

# Debian
for _arch in amd64 i386 ; do
  # Installation media
  for _medium in 'cd' 'dvd'; do
    _page="https://cdimage.debian.org/debian-cd/current/$_arch/bt-$_medium/"
    __download "$_page" | grep -Eo 'href="[^"]+\.torrent' |
     grep -Eo '[^"]+\.torrent' |
      while read -r _rel_link; do
        printf '%s%s\n' "$_page" "$_rel_link"
      done
  done
  # Live CD
  _page="https://cdimage.debian.org/debian-cd/current-live/$_arch/bt-hybrid/"
  __download "$_page" | grep -Eo 'href="[^"]+\.torrent' |
   grep -Eo '[^"]+\.torrent' |
    while read -r _rel_link; do
      printf '%s%s\n' "$_page" "$_rel_link"
    done
done

# Ubuntu
__download 'https://www.ubuntu.com/download/alternative-downloads' |
 grep -Eo 'href="[^"]+\.torrent' | grep -Eo '[^"]+\.torrent'

# openSUSE
__download 'https://software.opensuse.org/distributions/leap' |
 grep -Eo 'href="[^"]+\.torrent' | grep -Eo '[^"]+\.torrent'

# Linux Mint
# It's not trivial to get a page with the latest torrents

# Fedora
# Doesn't seem to provide torrents..?

# Elementary
__download 'https://elementary.io' | grep -Eo 'magnet:[^"]+'

# CentOS
# It's not trivial to get a page with the latest torrents

# TrueOS
__download 'http://download.trueos.org/master/amd64/' |
 grep -Eo 'href="[^"]+\.torrent' | grep -Eo '[^"]+\.torrent' |
  while read -r _rel_link; do
    printf '%s%s\n' 'http://download.trueos.org/master/amd64/' "$_rel_link"
  done

# ReactOS
# Uses sourceforge to distribute its isos

# Kali
# https://www.kali.org/downloads/ forces gzip encoding. I'm not dealing with
# this crap. Learn how to configure your webserver.

# KDE Neon
# Doesn't seem to provide torrents..?

# Mageia
# It's not trivial to get a page with the latest torrents

# tails
__download 'https://tails.boum.org/torrents/files/' |
 grep -Eo 'href="[^"]+\.torrent' | grep -Eo '[^"]+\.torrent' |
  while read -r _rel_link; do
    printf '%s%s\n' 'https://tails.boum.org/torrents/files/' "$_rel_link"
  done

