#!/bin/sh

# Usage:
# $ ix ./file
# $ ix some command
# $ some command | ix

# The explanation of the following code is left as an exercise to the user

[ "$(id -u)" -gt 0 ] && p='%' || p='#'

__ix () {
    [ -z "$1" -o -r "$1" ] && curl -F "f:1=<${1:--}" ix.io ||
      printf '%s %s\n\n%s' "$p" "$*" "$("$@")" 2>&1 | __ix
}

__ix "$@"
