#!/bin/sh

# Runs urxvt after loading a specific Xresources file.
#
# The command that is run is the comment on the first line of the
# ~/.config/X/Xresources."$1" file. For example:
#
# ! ssh myserver.example.com
# or
# ! su - -c "tmux a"

_profile="$1"
_file=~/.config/X/Xresources."$_profile"

if [ -f "$_file" ]; then
  command="$(head -n1 "$_file" | sed -n "s/^!\\s//p;")"
  XENVIRONMENT="$_file" urxvt -e sh -c "$command" &
else
  exit 1
fi
