#!/bin/sh

# Locks the screen, pauses (kill -STOP) some processes

# USAGE:   lockscreen LOCKER APPS TO STOP
# EXAMPLE: lockscreen xsecurelock chromium mpv

_locker="${1:-xsecurelock}"
shift

__pause() {
  pkill -STOP "$1"
  while pgrep "$_locker" >/dev/null; do
    sleep 1
  done
  pkill -CONT "$1"
}

"$_locker" &

for _prog in "$@"; do
  __pause "$_prog" &
done
