#!/bin/sh

#set -x

: "${_src_dir="/usr/src"}"
: "${_tgz_dir="/usr/rel"}"

__usage () {
  cat << EOH
Update or initialize ${_src_dir} with OpenBSD's source.

$0 -h|help
$0 init
$0 update

init will: check for presence of the src and sys archives in ${_tgz_dir};
           validate them (sha256);
           clean ${_src_dir};
           decompress the tarballs;

update will: cd to ${_src_dir};
             launch the CVS command to follow -stable.
         >>  Don't forget to set \$CVSROOT
             $CVSROOT
EOH
}

case "$1" in
  -h|help)
    __usage ; exit 0
  ;;
  init)
    cd $_tgz_dir || exit 2

    : "${_src_tgz="src.tar.gz"}"
    : "${_sys_tgz="sys.tar.gz"}"
    : "${_sha="SHA256"}"

    if [ ! -r "$_sha" ]; then
      printf '%s\n' "I won't do anything reckless: please download the SHA256 file" \
        "https://mirrors.evowise.com/pub/OpenBSD/$(uname -r)/SHA256" >&2
      exit 3
    fi

    __status () {
      printf ':: %s\n' "$1"
    }

    while ! sha256 -C "$_sha" "$_src_tgz"; do
      __status "Downloading $_src_tgz"
      ftp -o "$_src_tgz" https://mirrors.evowise.com/pub/OpenBSD/"$(uname -r)"/src.tar.gz
    done

    while ! sha256 -C "$_sha" "$_sys_tgz"; do
      __status "Downloading $_sys_tgz"
      ftp -o "$_sys_tgz" https://mirrors.evowise.com/pub/OpenBSD/"$(uname -r)"/sys.tar.gz
    done

    __status "Cleaning up $_src_dir, this might take a while"
    rm -r "${_src_dir:?}"/*
    __status "Deflating $_src_tgz"
    mkdir -p "$_src_dir"
    tar xzf "$_src_tgz" -C "$_src_dir"
    __status "Deflating $_sys_tgz"
    tar xzf "$_sys_tgz" -C "$_src_dir"
  ;;
  update)
    cd "$_src_dir" || exit 4
    # cvs will fail if there is no CVSROOT specified
    # example: CVSROOT=anoncvs@anoncvs.fr.openbsd.org:/cvs <command>
    # list of CVSROOTs that could work: https://www.openbsd.org/anoncvs.html#CVSROOT
    cvs -q up -rOPENBSD_"$(uname -r | sed 's/\./_/')" -Pd
    exit $?
  ;;
  *)
    __usage >&2 ; exit 5
  ;;
esac

