#!/bin/sh

set -e

: "${_tgz_dir="/usr/rel"}"
: "${_sha="SHA256"}"
: "${_sha_sig="SHA256.sig"}"
_rel="${2:-"$(uname -r)"}"
_rel_underscore="$(printf '%s' "$_rel" | sed 's/\./_/')"
_rel_nodot="$(printf '%s' "$_rel" | sed 's/\.//')"
: "${_arch="$(uname -m)"}"

__status () {
  printf ':: %s\n' "$1" >&2
}

__verify () {
  __status "Verifying $1"
  signify -C -q -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" -x \
   "$_sha_sig" "$1"
}

case "$1" in 
  fetch)
    cd "$_tgz_dir"
    # We download both SHA256.sig and SHA256 as base of truth
    for _h in "${_sha}" "${_sha_sig}"; do
      __status "Downloading $_h"
      ftp -o "$_h" \
       "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/${_arch}/${_h}" \
       >/dev/null
    done

    # Check SHA256 against known signature keys (on current system)
    __status "Checking ${_sha} and ${_sha_sig}"
    signify -V -q -x "${_sha_sig}" \
     -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" -m "${_sha}"

    # We download the archives until signify checks out
    for _f in base${_rel_nodot}.tgz game${_rel_nodot}.tgz \
     comp${_rel_nodot}.tgz man${_rel_nodot}.tgz bsd bsd.mp bsd.rd; do
      while ! __verify "$_f"; do
        __status "Downloading $_f"
        ftp -o "$_f" \
         "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/${_arch}/${_f}" \
         >/dev/null
      done
    done
  ;;
esac
