#!/bin/sh

#set -x
set -e

: "${_src_dir="/usr/src"}"
: "${_tgz_dir="/usr/rel"}"
: "${_src_tgz="src.tar.gz"}"
: "${_sys_tgz="sys.tar.gz"}"
: "${_sha="SHA256"}"
: "${_sha_sig="SHA256.sig"}"
_rel="${2:-"$(uname -r)"}"
_rel_underscore="$(printf '%s' "$_rel" | sed 's/\./_/')"
_rel_nodot="$(printf '%s' "$_rel" | sed 's/\.//')"

__usage () {
  cat << EOH
Update or initialize ${_src_dir} with OpenBSD's source.

$0 -h|help
$0 init
$0 update

init will: check for presence of the src and sys archives in ${_tgz_dir};
           validate them (sha256);
           clean ${_src_dir};
           decompress the tarballs;

update will: cd to ${_src_dir};
             launch the CVS command to follow -stable.
         >>  Don't forget to set \$CVSROOT
             $CVSROOT
EOH
}

__status () {
  printf ':: %s\n' "$1"
}

case "$1" in
  -h|help)
    __usage ; exit 0
  ;;
  init)
    cd $_tgz_dir

    # Check SHA256 against known signature keys (on current system)
    while ! signify -V -q -x "${_sha_sig}" \
     -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" -m "${_sha}"; do
      # We download both SHA256 and SHA256.sig to avoid endless loops if we get a broken SHA256.sig
      __status "Downloading SHA256.sig"
      ftp -o "$_sha_sig" \
       "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/SHA256.sig" >&2
      __status "Downloading SHA256"
      ftp -o "$_sha" \
       "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/SHA256" >&2
    done

    while ! signify -C -q -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" \
     -x "$_sha_sig" "$_src_tgz"; do
      __status "Downloading $_src_tgz"
      ftp -o "$_src_tgz" "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/src.tar.gz"
    done

    while ! signify -C -q -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" \
     -x "$_sha_sig" "$_sys_tgz"; do
      __status "Downloading $_sys_tgz"
      ftp -o "$_sys_tgz" "https://mirrors.evowise.com/pub/OpenBSD/${_rel}/sys.tar.gz"
    done

    __status "Verifying $_src_tgz and $_sys_tgz"
    signify -C -q -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" -x "$_sha_sig" "$_src_tgz"
    signify -C -q -p "/etc/signify/openbsd-${_rel_nodot}-base.pub" -x "$_sha_sig" "$_sys_tgz"
    __status "Cleaning up $_src_dir, this might take a while"
    rm -r "${_src_dir:?}"/*
    __status "Deflating $_src_tgz"
    mkdir -p "$_src_dir"
    tar xzf "$_src_tgz" -C "$_src_dir"
    __status "Deflating $_sys_tgz"
    tar xzf "$_sys_tgz" -C "$_src_dir"
  ;;
  update)
    cd "$_src_dir"
    # cvs will fail if there is no CVSROOT specified
    # example: CVSROOT=anoncvs@anoncvs.fr.openbsd.org:/cvs <command>
    # list of CVSROOTs that could work: https://www.openbsd.org/anoncvs.html#CVSROOT
    cvs -q up -rOPENBSD_"${_rel_underscore}" -Pd
  ;;
  *)
    __usage >&2 ; exit 5
  ;;
esac

