#!/bin/sh
#
# Original Author: Moviuro
# Distributed under the terms of the WTFPL.
#
# You can find a full copy of the license here:
#      http://www.wtfpl.net/txt/copying/

# This script sends an SMS using the Free Mobile API, see
# https://www.freenews.fr/freenews-edition-nationale-299/free-mobile-170/nouvelle-option-notifications-par-sms-chez-free-mobile-14817

set -ex

_myname="$(basename "$0")"

if [ -r "$HOME/.config/$_myname.rc" ]; then
  . "$HOME/.config/$_myname.rc"
fi

# read arguments
while getopts ":u:p:" _opt; do
  case "$_opt" in
    u) user="$OPTARG" ;;
    p) pass="$OPTARG" ;;
  esac
done

shift $((OPTIND-1))

if [ -z "$user" -o -z "$pass" -o -z "$1" ]; then
  printf '%s\n' "A parameter is missing: user, pass or message" >&2
  exit 1
fi

curl -G https://smsapi.free-mobile.fr/sendmsg -d "user=$user" \
  -d "pass=$pass" --data-urlencode "msg=$(hostname) message: $1"
