#!/bin/sh

# This script sends an SMS using the Free Mobile API, see
# https://www.freenews.fr/freenews-edition-nationale-299/free-mobile-170/nouvelle-option-notifications-par-sms-chez-free-mobile-14817

set -e

# read arguments
while getopts ":u:p:v" _opt; do
  case "$_opt" in
    u) user="$OPTARG" ;;
    p) pass="$OPTARG" ;;
    v) set -x         ;;
  esac
done

_myname="$(basename "$0")"

if [ -r "$HOME/.config/$_myname.rc" ]; then
  . "$HOME/.config/$_myname.rc"
fi

shift $((OPTIND-1))

if [ -z "$user" -o -z "$pass" ]; then
  printf '%s\n' "A parameter is missing: user or pass" >&2
  exit 1
fi

{
  printf '%s\n' "$(hostname) message:"
  if [ -z "$1" ]; then
    cat -
  else
    echo "$1"
  fi
} | curl -G https://smsapi.free-mobile.fr/sendmsg -d "user=$user" \
    -d "pass=$pass" --data-urlencode msg@-
