#!/bin/sh

# Usage:
# $ x0 ./file
# $ x0 some command
# $ some command | x0

# The explanation of the following code is left as an exercise to the user

__x0 () {
    [ -z "$1" -o -r "$1" ] && curl -F "file=@${1:--}" \
      https://x0.at ||
      printf '$%s\n\n%s' "$*" "$("$@")" 2>&1 | __x0
}

__x0 "$@"
